# Generated by Django 5.1.6 on 2025-05-21 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rczp', '0002_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='birth',
            field=models.DateField(default='2025-05-21', max_length=20, verbose_name='出生日期'),
        ),
    ]
