# Generated by Django 5.2.2 on 2025-06-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rczp", "0003_alter_resume_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="birth",
            field=models.DateField(
                default="2025-06-09", max_length=20, verbose_name="出生日期"
            ),
        ),
    ]
