# Generated by Django 5.1.6 on 2025-04-09 04:56

import DjangoUeditor.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name=' 标题')),
                ('description', DjangoUeditor.models.UEditorField(default='', verbose_name='内容')),
                ('newType', models.CharField(choices=[('招商专区', '招商专区'), ('成功案例', '成功案例'), ('空间入驻', '空间入驻')], max_length=50, verbose_name='类型')),
                ('publishDate', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='发布时间')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
                'ordering': ['-publishDate'],
            },
        ),
    ]
