# Generated by Django 5.2.2 on 2025-06-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test2", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mynew",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="news/", verbose_name="展报"
            ),
        ),
    ]
