# Generated by Django 5.1.6 on 2025-04-06 10:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name=' 电视剧名称')),
                ('description', models.TextField(verbose_name='剧情介绍')),
                ('TVType', models.CharField(choices=[('现代电视剧', '现代电视剧'), ('古装电视剧', '古装电视剧')], max_length=50, verbose_name='电视剧类型')),
                ('publishDate', models.DateTimeField(default=datetime.datetime(2025, 4, 6, 10, 52, 3, 718579, tzinfo=datetime.timezone.utc), max_length=20, verbose_name='发布时间')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
            ],
            options={
                'verbose_name': '电视剧',
                'verbose_name_plural': '电视剧',
                'ordering': ('-publishDate',),
            },
        ),
        migrations.CreateModel(
            name='TVImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='movie/', verbose_name='剧照')),
                ('tv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TVImgs', to='test3.tv', verbose_name='电视剧')),
            ],
            options={
                'verbose_name': '剧照',
                'verbose_name_plural': '剧照',
            },
        ),
    ]
