# Generated by Django 5.1.6 on 2025-04-09 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv',
            name='publishDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 9, 4, 56, 28, 474093, tzinfo=datetime.timezone.utc), max_length=20, verbose_name='发布时间'),
        ),
    ]
