# Generated by Django 5.1.6 on 2025-04-26 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test3', '0002_alter_tv_publishdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv',
            name='publishDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 26, 8, 44, 13, 536832, tzinfo=datetime.timezone.utc), max_length=20, verbose_name='发布时间'),
        ),
    ]
