# Generated by Django 5.1.6 on 2025-05-05 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test3', '0004_alter_tv_publishdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv',
            name='publishDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 5, 13, 10, 49, 194553, tzinfo=datetime.timezone.utc), max_length=20, verbose_name='发布时间'),
        ),
    ]
