# Generated by Django 5.1.6 on 2025-05-21 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test3', '0007_alter_tv_publishdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tv',
            name='publishDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 21, 6, 1, 59, 293392, tzinfo=datetime.timezone.utc), max_length=20, verbose_name='发布时间'),
        ),
    ]
