# Generated by Django 5.2.2 on 2025-06-09 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test3", "0008_alter_tv_publishdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tv",
            name="publishDate",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 6, 9, 14, 3, 15, 825348, tzinfo=datetime.timezone.utc
                ),
                max_length=20,
                verbose_name="发布时间",
            ),
        ),
    ]
